Repository intel/cve-bin-tool, pull requests merged in 2020-07, with the labels that each got.

#798 [Part 1] Improved error handling with beautiful trace and exit code in cli, input_engine and cvedb
  cve_bin_tool/cli.py
  cve_bin_tool/csv2cve.py
  cve_bin_tool/cvedb.py
  cve_bin_tool/error_handler.py
  cve_bin_tool/input_engine.py
  test/test_cli.py
  test/test_input_engine.py
Labels: awaiting changes

#790 Refactored Outputengine
  cve_bin_tool/output_engine.py
  cve_bin_tool/output_engine/__init__.py
  cve_bin_tool/output_engine/console.py
  cve_bin_tool/output_engine/html.py
  cve_bin_tool/output_engine/html_reports/Example/example.html
  cve_bin_tool/output_engine/html_reports/css/bootstrap.min.css
  cve_bin_tool/output_engine/html_reports/css/main.css
  cve_bin_tool/output_engine/html_reports/js/bootstrap.min.js
  cve_bin_tool/output_engine/html_reports/js/jquery-3.4.1.slim.min.js
  cve_bin_tool/output_engine/html_reports/js/main.js
  cve_bin_tool/output_engine/html_reports/js/plotly-latest.min.js
  cve_bin_tool/output_engine/html_reports/templates/base.html
  cve_bin_tool/output_engine/html_reports/templates/dashboard.html
  cve_bin_tool/output_engine/html_reports/templates/row_cve.html
  cve_bin_tool/output_engine/html_reports/templates/row_product.html
  cve_bin_tool/output_engine/util.py
  test/test_output_engine.py
Labels: awaiting changes

#826 Improved error handling and readability of extractor
  cve_bin_tool/cli.py
  cve_bin_tool/extractor.py
  cve_bin_tool/version_scanner.py
  test/test_cli.py
  test/test_extractor.py
Labels: awaiting maintainer

#842 Add checker for qt
  cve_bin_tool/checkers/__init__.py
  cve_bin_tool/checkers/qt.py
  test/test_data/__init__.py
  test/test_data/qt.py
Labels: awaiting response

#840 Add mysql checker
  cve_bin_tool/checkers/__init__.py
  cve_bin_tool/checkers/mysql.py
  test/test_data/__init__.py
  test/test_data/mysql.py
Labels: awaiting changes
