Repository intel/cve-bin-tool, pull requests merged in 2020-04, with the labels that each got.

#540 Add test using real files for libgcrypt
  test/binaries/test-libgcrypt-1.6.0.c
  test/test_scanner.py
Labels: awaiting response

#533 Add test using real files for png
  test/binaries/test-png-1.5.12.c
  test/test_scanner.py
Labels: awaiting response

#549 Add test using real files for sqlite
  test/binaries/test-sqlite-3.16.1.c
  test/test_scanner.py
Labels: awaiting response

#544 Add curl 7.65.0 signature & mapping test
  test/binaries/test-curl-7.65.0.c
  test/test_scanner.py
Labels: awaiting changes

#548 Added tests for python2.7, since a lot of projects still use this version
  cve_bin_tool/checkers/python.py
  test/binaries/test-python-2.7.c
  test/test_checkers.py
  test/test_scanner.py
Labels: awaiting changes

#514 Add lighttpd checker
  cve_bin_tool/checkers/__init__.py
  cve_bin_tool/checkers/lighttpd.py
  test/binaries/test-lighttpd-1.4.30.c
  test/test_scanner.py
Labels: awaiting changes

#473 Better console conventions - decouple console format logic from output formatting, ensure stdout is for output only
  MANUAL.md
  README.md
  cve_bin_tool/OutputEngine.py
  cve_bin_tool/cli.py
  cve_bin_tool/log.py
Labels: awaiting response

#551 flatten output of json and refactored output engine code
  cve_bin_tool/OutputEngine.py
  test/test_output_engine.py
Labels: awaiting changes

#535 fixed test_string, test_extract and test_checker on Windows
  .github/workflows/pythonapp.yml
  cve_bin_tool/extractor.py
  test/test_checkers.py
  test/test_extract.py
  test/test_strings.py
Labels: awaiting maintainer
