Repository intel/cve-bin-tool, pull requests merged in 2022-07, with the labels that each got.

#1739 test: unit tests for version.py
  test/test_version.py
Labels: awaiting maintainer

#1722 refactor: refactor javascript parser (#1721)
  cve_bin_tool/parsers/__init__.py
  cve_bin_tool/parsers/javascript.py
  cve_bin_tool/version_scanner.py
Labels: awaiting maintainer

#1772 refactor: refactor java parser (#1771)
  cve_bin_tool/parsers/__init__.py
  cve_bin_tool/parsers/java.py
  cve_bin_tool/version_scanner.py
Labels: awaiting maintainer

#1743 feat: add rust support (#1723)
  README.md
  cve_bin_tool/parsers/__init__.py
  cve_bin_tool/parsers/rust.py
  cve_bin_tool/version_scanner.py
  test/language_data/Cargo.lock
  test/test_language_scanner.py
Labels: awaiting maintainer

#1665 chore: Updated requirements.txt
  .github/workflows/testing.yml
  dev-requirements.txt
  requirements.csv
  requirements.txt
Labels: awaiting CI

#1750 feat(data_source): OSV
  .github/actions/spelling/allow.txt
  README.md
  cve_bin_tool/cli.py
  cve_bin_tool/cve_scanner.py
  cve_bin_tool/cvedb.py
  cve_bin_tool/data_sources/curl_source.py
  cve_bin_tool/data_sources/nvd_source.py
  cve_bin_tool/data_sources/osv_source.py
  requirements.csv
  requirements.txt
  test/test_nvd_api.py
Labels: awaiting maintainer, dependencies
