Repository intel/cve-bin-tool, pull requests merged in 2022-11, with the labels that each got.

#2301 feat(checker): add miniupnpc checker
  cve_bin_tool/checkers/__init__.py
  cve_bin_tool/checkers/miniupnpc.py
  test/condensed-downloads/libminiupnpc17_2.2.3-1+b1_amd64.deb.tar.gz
  test/condensed-downloads/libminiupnpc_2.2.1-1_x86_64.ipk.tar.gz
  test/condensed-downloads/miniupnpc-2.1-1.fc30.aarch64.rpm.tar.gz
  test/test_data/miniupnpc.py
Labels: awaiting CI

#2303 refactor: fix mypy errors in checkers/[uz]*.py
  cve_bin_tool/checkers/unbound.py
  cve_bin_tool/checkers/unixodbc.py
  cve_bin_tool/checkers/upx.py
  cve_bin_tool/checkers/util_linux.py
  cve_bin_tool/checkers/vsftpd.py
  cve_bin_tool/checkers/wolfssl.py
  cve_bin_tool/checkers/xml2.py
  cve_bin_tool/checkers/xscreensaver.py
  cve_bin_tool/checkers/zeek.py
  cve_bin_tool/checkers/znc.py
Labels: awaiting CI

#2306 chore: fixed mypy issues in checkers/h*.py
  cve_bin_tool/checkers/haproxy.py
  cve_bin_tool/checkers/haserl.py
  cve_bin_tool/checkers/hostapd.py
Labels: awaiting CI

#2307 refactor: fix mypy issues in egg_updater.py
  cve_bin_tool/egg_updater.py
Labels: awaiting CI

#2321 feat: explicit option to load triage file
  README.md
  cve_bin_tool/cli.py
  cve_bin_tool/input_engine.py
  test/csv/test_triage_input.csv
  test/test_input_engine.py
  test/test_requirements.py
  test/test_triage.py
  test/vex/test_triage_triage_input.vex
  triage.json
Labels: awaiting maintainer

#2324 feat: Improve output report with multiple data sources (Fixes #2231)
  cve_bin_tool/output_engine/__init__.py
  cve_bin_tool/output_engine/console.py
  cve_bin_tool/output_engine/util.py
  test/test_output_engine.py
Labels: awaiting maintainer

#2350 feat(checker): add freerdp checker
  cve_bin_tool/checkers/__init__.py
  cve_bin_tool/checkers/freerdp.py
  test/condensed-downloads/freerdp-2.8.1-2-omv4090.aarch64.rpm.tar.gz
  test/condensed-downloads/libfreerdp-client2-2_2.0.0~git20190204.1.2693389a%2Bdfsg1-1~bpo9%2B1_amd64.deb.tar.gz
  test/test_data/freerdp.py
Labels: awaiting CI

#2386 refactor: Update types syntax in available_fix/*
  cve_bin_tool/available_fix/__init__.py
  cve_bin_tool/available_fix/debian_cve_tracker.py
  cve_bin_tool/available_fix/redhat_cve_tracker.py
Labels: awaiting CI

#2222 feat: Keep a copy of the NVD database (Fixes #1099)
  .github/workflows/export_data.yml
Labels: awaiting maintainer, dependencies

#2363 fix: remove use of tarfile
  cve_bin_tool/extractor.py
  test/test_cli.py
  test/test_extractor.py
Labels: awaiting CI

#2397 refactor: Updates typehint to newer sintax
  cve_bin_tool/output_engine/__init__.py
  cve_bin_tool/output_engine/console.py
  cve_bin_tool/output_engine/html.py
  cve_bin_tool/output_engine/print_mode.py
  cve_bin_tool/output_engine/util.py
Labels: awaiting CI
