Repository intel/cve-bin-tool, pull requests merged in 2022-08, with the labels that each got.

#1826 feat: create parse api (#1810)
  cve_bin_tool/parsers/parse.py
  cve_bin_tool/version_scanner.py
  test/test_language_scanner.py
Labels: awaiting response

#1868 fix: quality issues reported by LGTM
  cve_bin_tool/data_sources/__init__.py
  cve_bin_tool/output_engine/console.py
Labels: awaiting maintainer, awaiting CI

#1869 chore: change unable to fetch osv warning to error
  cve_bin_tool/data_sources/osv_source.py
Labels: awaiting maintainer, awaiting CI

#1885 feat: improve behaviour for -i when specified file is binary
  cve_bin_tool/cli.py
Labels: awaiting CI

#1875 fix: database schema not checked if no update flag set
  cve_bin_tool/cli.py
  cve_bin_tool/cvedb.py
Labels: awaiting CI

#1589 feat(checker): add apache http support
  cve_bin_tool/checkers/__init__.py
  cve_bin_tool/checkers/apache_http_server.py
  test/condensed-downloads/httpd-2.4.51-2.fc35.x86_64.rpm.tar.gz
  test/test_checkers.py
  test/test_data/apache_http_server.py
Labels: awaiting maintainer
