Repository intel/cve-bin-tool, pull requests merged in 2023-06, with the labels that each got.

#2913 feat: merged report content change and comments added in html reports
  cve_bin_tool/merge.py
  cve_bin_tool/output_engine/html.py
  cve_bin_tool/output_engine/html_reports/templates/row_cve.html
  cve_bin_tool/output_engine/print_mode/templates/content.html
  cve_bin_tool/output_engine/util.py
  doc/MANUAL.md
  test/pages/html_report.py
  test/test_html.py
Labels: awaiting CI

#2882 feat: add support for pgp signing (#2577)
  cve_bin_tool/cli.py
  cve_bin_tool/cvedb.py
  cve_bin_tool/error_handler.py
  cve_bin_tool/fetch_json_db.py
  requirements.csv
  requirements.txt
  test/test_cvedb.py
  test/test_fetch_json_db.py
Labels: awaiting maintainer, dependencies

#2999 feat(checker): add udisks checker
  cve_bin_tool/checkers/__init__.py
  cve_bin_tool/checkers/udisks.py
  test/condensed-downloads/udisks-2.9.4-5-omv4090.aarch64.rpm.tar.gz
  test/condensed-downloads/udisks2_2.8.1-4_amd64.deb.tar.gz
  test/test_data/udisks.py
Labels: awaiting CI

#2976 feat(checker): add readline checker
  cve_bin_tool/checkers/__init__.py
  cve_bin_tool/checkers/readline.py
  test/condensed-downloads/libreadline7_7.0-5_amd64.deb.tar.gz
  test/condensed-downloads/libreadline8_8.0-1_x86_64.ipk.tar.gz
  test/condensed-downloads/readline-8.2-3.fc38.aarch64.rpm.tar.gz
  test/test_data/readline.py
Labels: awaiting CI

#2973 feat(checker): add ntfs-3g checker
  cve_bin_tool/checkers/__init__.py
  cve_bin_tool/checkers/ntfs_3g.py
  test/condensed-downloads/ntfs-3g-2022.10.3-2.fc38.aarch64.rpm.tar.gz
  test/condensed-downloads/ntfs-3g_2017.3.23-3-fuseint_x86_64.ipk.tar.gz
  test/condensed-downloads/ntfs-3g_2017.3.23AR.3-3+deb10u2_amd64.deb.tar.gz
  test/test_data/ntfs_3g.py
Labels: awaiting CI

#3002 feat(checker): add libmodbus checker
  cve_bin_tool/checkers/__init__.py
  cve_bin_tool/checkers/libmodbus.py
  test/condensed-downloads/libmodbus-3.1.6-5.fc38.aarch64.rpm.tar.gz
  test/condensed-downloads/libmodbus5_3.1.4-2+deb10u1_amd64.deb.tar.gz
  test/condensed-downloads/libmodbus_3.1.6-1_x86_64.ipk.tar.gz
  test/test_data/libmodbus.py
Labels: awaiting CI

#3001 feat(checker): add coreutils checker
  cve_bin_tool/checkers/__init__.py
  cve_bin_tool/checkers/coreutils.py
  test/condensed-downloads/coreutils-9.3-1.2.i586.rpm.tar.gz
  test/condensed-downloads/coreutils-base64_8.30-2_x86_64.ipk.tar.gz
  test/condensed-downloads/coreutils_8.30-3_amd64.deb.tar.gz
  test/test_data/coreutils.py
Labels: awaiting CI

#2993 fix: improve luajit checker
  cve_bin_tool/checkers/luajit.py
  test/test_data/luajit.py
  test/test_data/snort.py
Labels: awaiting CI

#2992 fix: improve gimp checker
  cve_bin_tool/checkers/gimp.py
  test/test_data/gimp.py
  test/test_data/stellarium.py
Labels: awaiting CI

#2991 fix: improve nghttp2 checker
  cve_bin_tool/checkers/nghttp2.py
  test/test_data/nghttp2.py
  test/test_data/node.py
  test/test_data/wireshark.py
Labels: awaiting CI

#2655 chore: removing support for Python3.7
  .github/workflows/sbom.yml
  .github/workflows/testing.yml
  .pre-commit-config.yaml
  .readthedocs.yml
  cve_bin_tool/cli.py
  cve_bin_tool/csv2cve.py
  doc/MANUAL.md
  setup.py
  test/test_cli.py
  test/test_extractor.py
  test/test_helper_script.py
  test/test_requirements.py
  test/test_strings.py
Labels: blocked, awaiting maintainer, awaiting CI
