Repository intel/cve-bin-tool, pull requests merged in 2023-03, with the labels that each got.

#2392 Refactor: Update types syntax in cve_bin_too/*.py
  cve_bin_tool/async_utils.py
  cve_bin_tool/cli.py
  cve_bin_tool/csv2cve.py
  cve_bin_tool/error_handler.py
  cve_bin_tool/format_checkers.py
  cve_bin_tool/merge.py
  cve_bin_tool/nvd_api.py
  cve_bin_tool/version_signature.py
Labels: awaiting CI

#2714 fix: improve ipmitool checker
  cve_bin_tool/checkers/ipmitool.py
Labels: awaiting CI

#2771 fix: remaining mypy errors in nvd_api.py #2764 #2767
  cve_bin_tool/nvd_api.py
Labels: awaiting CI

#2781 fix: remaining mypy errors in csv2cve.py
  cve_bin_tool/csv2cve.py
Labels: awaiting CI

#2699 feat: Config generator
  cve_bin_tool/cli.py
  cve_bin_tool/config_generator.py
  test/test_cli.py
Labels: awaiting maintainer, awaiting CI

#2804 feat(checker): add u-boot checker
  cve_bin_tool/checkers/__init__.py
  cve_bin_tool/checkers/u_boot.py
  cve_bin_tool/version_scanner.py
  test/condensed-downloads/trimslice-spi.img.tar.gz
  test/condensed-downloads/u-boot-mtk.bin.tar.gz
  test/condensed-downloads/u-boot-rpi_2016.11+dfsg1-4_arm64.deb.tar.gz
  test/condensed-downloads/u-boot-tegra_2023.04~rc2+dfsg-1_arm64.deb.tar.gz
  test/test_data/u_boot.py
Labels: awaiting CI

#2807 fix: export database ci
  .github/workflows/export_data.yml
Labels: blocked, awaiting maintainer

#2785 chore: fixes most mypy errors in file output_engine/util.py
  cve_bin_tool/output_engine/util.py
Labels: awaiting response

#2757 feat(checker): add pcre checker
  cve_bin_tool/checkers/__init__.py
  cve_bin_tool/checkers/pcre.py
  test/condensed-downloads/libpcre_8.43-1_x86_64.ipk.tar.gz
  test/condensed-downloads/pcre-8.45-1.fc38.3.aarch64.rpm.tar.gz
  test/test_data/pcre.py
Labels: awaiting CI

#2839 fix: -1 values were replaced with positive integer error codes (fixes #2838)
  cve_bin_tool/cli.py
  cve_bin_tool/error_handler.py
Labels: awaiting CI

#2786 fix: mypy errors in `output_engine/html.py`
  cve_bin_tool/output_engine/html.py
  cve_bin_tool/output_engine/util.py
Labels: awaiting CI

#2809 fix: GAD source version parsing (#2793)
  cve_bin_tool/data_sources/gad_source.py
  test/test_cli.py
  test/test_source_gad.py
Labels: awaiting maintainer

#2565 feat: add ceph checker
  .github/actions/spelling/allow.txt
  cve_bin_tool/checkers/__init__.py
  cve_bin_tool/checkers/ceph.py
  test/condensed-downloads/ceph-17.2.5-13.fc39.aarch64.rpm.tar.gz
  test/condensed-downloads/ceph-base_10.2.11-2_amd64.deb.tar.gz
  test/condensed-downloads/ceph_14.2.21-1_amd64.deb.tar.gz
  test/test_data/ceph.py
Labels: awaiting response

#2780 feat(checker): add f2fs-tools checker
  cve_bin_tool/checkers/__init__.py
  cve_bin_tool/checkers/f2fs_tools.py
  test/condensed-downloads/f2fs-tools-1.15.0-2.1.aarch64.rpm.tar.gz
  test/condensed-downloads/f2fs-tools_1.15.0-1_amd64.deb.tar.gz
  test/condensed-downloads/f2fs-tools_1.4.0-2_amd64.deb.tar.gz
  test/condensed-downloads/f2fsck_1.14.0-3_x86_64.ipk.tar.gz
  test/test_data/f2fs_tools.py
Labels: awaiting CI

#2836 feat(checker): add zabbix checker
  cve_bin_tool/checkers/__init__.py
  cve_bin_tool/checkers/zabbix.py
  test/condensed-downloads/zabbix-6.0.13-2.fc39.aarch64.rpm.tar.gz
  test/condensed-downloads/zabbix-server-mysql_4.0.4+dfsg-1_amd64.deb.tar.gz
  test/condensed-downloads/zabbix-server_4.0.37-1_x86_64.ipk.tar.gz
  test/test_data/zabbix.py
Labels: awaiting CI
