Repository intel/cve-bin-tool, pull requests merged in 2023-10, with the labels that each got.

#3353 feat(checker): extended BindChecker
  cve_bin_tool/checkers/bind.py
  test/test_checkers.py
Labels: awaiting CI

#3362 test: improve flaky java language scanner test
  test/language_data/pom.xml
  test/test_language_scanner.py
Labels: awaiting CI

#3381 docs: Add missing docstrings fetch_json_db.py
  cve_bin_tool/fetch_json_db.py
Labels: awaiting CI

#3382 Fix : add missing docstrings to package_list_parser.py #3377
  cve_bin_tool/package_list_parser.py
Labels: awaiting CI

#3373 feat: Add purl support for SBOMs
  cve_bin_tool/sbom_manager/__init__.py
  requirements.csv
  requirements.txt
  test/test_sbom.py
Labels: dependencies

#3392 docs: add missing docstrings to cvedb.py
  cve_bin_tool/cvedb.py
Labels: awaiting CI

#3387 docs: add missing docstrings to cli.py
  cve_bin_tool/cli.py
Labels: awaiting CI

#3267 feat: add latest upstream stable version in CPE summary
  cve_bin_tool/cli.py
  cve_bin_tool/output_engine/__init__.py
  cve_bin_tool/output_engine/console.py
  cve_bin_tool/output_engine/util.py
  test/test_output_engine.py
Labels: awaiting maintainer, dependencies

#3444 test: add non-debian based test for dosfstools
  test/condensed-downloads/dosfstools-4.2-6.fc38.x86_64.rpm.tar.gz
  test/condensed-downloads/dosfstools_4.2-2_x86_64.ipk.tar.gz
  test/test_data/dosfstools.py
Labels: awaiting CI

#3469 docs: added missing GAD_Source docstrings
  cve_bin_tool/data_sources/gad_source.py
Labels: awaiting CI

#3445 Testing CVE-Bin-Tool with Python 3.12 on Github
  .github/workflows/testing.yml
Labels: awaiting CI

#3490 fix: Added None checks for parsed purls (fixes #3478)
  cve_bin_tool/sbom_manager/__init__.py
  test/sbom/cyclonedx_mixed_test.json
Labels: awaiting CI

#3496 Ci: Change workflows to use python 3.11
  .github/workflows/formatting.yml
  .github/workflows/linting.yml
  .github/workflows/testing.yml
  .github/workflows/update-js-dependencies.yml
  .github/workflows/update-pre-commit.yml
Labels: awaiting CI
