Repository intel/cve-bin-tool, pull requests merged in 2023-02, with the labels that each got.

#2525 fix: improve nginx checker
  cve_bin_tool/checkers/nginx.py
  test/condensed-downloads/nginx-full_1.10.3-1+deb9u4_amd64.deb.tar.gz
  test/condensed-downloads/nginx_1.17.7-3_x86_64.ipk.tar.gz
  test/test_data/nginx.py
Labels: awaiting CI

#2474 ci: re-enabling disabled tests
  test/test_cli.py
  test/test_cvedb.py
Labels: awaiting maintainer, awaiting CI

#2608 fix: wrong pip version slicing
  cve_bin_tool/parsers/python.py
Labels: awaiting CI

#2500 fix: improve glibc checker
  cve_bin_tool/checkers/README.md
  cve_bin_tool/checkers/glibc.py
  test/condensed-downloads/libc-bin_2.19-18+deb8u10_amd64.deb.tar.gz
  test/condensed-downloads/libc6-amd64_2.24-11+deb9u4_i386.deb.tar.gz
  test/test_checkers.py
  test/test_data/glibc.py
  test/test_data/grub2.py
Labels: blocked

#2653 feat(checker): add rauc
  cve_bin_tool/checkers/__init__.py
  cve_bin_tool/checkers/rauc.py
  test/condensed-downloads/rauc_1.5.1-1_amd64.deb.tar.gz
  test/condensed-downloads/rauc_1.8-2_arm64.deb.tar.gz
  test/test_data/rauc.py
Labels: awaiting CI

#2729 ci: Change "Formatting" workflow name to "Update checkers table"
  .github/workflows/formatting.yml
Labels: awaiting CI

#2717 feat(checker): add harfbuzz
  cve_bin_tool/checkers/__init__.py
  cve_bin_tool/checkers/harfbuzz.py
  test/condensed-downloads/harfbuzz-1.7.5-2.el7.aarch64.rpm.tar.gz
  test/condensed-downloads/harfbuzz-7.0.0-2.fc39.aarch64.rpm.tar.gz
  test/condensed-downloads/libharfbuzz-bin_1.4.2-1_amd64.deb.tar.gz
  test/condensed-downloads/libharfbuzz0b_0.9.35-2_amd64.deb.tar.gz
  test/condensed-downloads/libharfbuzz0b_6.0.0+dfsg-3_amd64.deb.tar.gz
  test/test_data/harfbuzz.py
Labels: awaiting CI
