Repository intel/cve-bin-tool, pull requests merged in 2024-03, with the labels that each got.

#3812 feat: add extraction enhancements to include binary identification
  cve_bin_tool/extractor.py
  requirements.csv
  requirements.txt
  test/test_extractor.py
Labels: dependencies, awaiting CI

#3882 test: OSV ecosystems to check for missing and extra ecosytems
  test/test_source_osv.py
Labels: awaiting maintainer

#3843 docs: Add docstrings to pdfbuilder.py
  cve_bin_tool/output_engine/pdfbuilder.py
Labels: awaiting CI

#3913 fix: tempfile cleanup for Go fuzzer
  fuzz/fuzz_go.py
Labels: awaiting CI

#3700 feat(checker): add System.net.http checker (#35)
  cve_bin_tool/checkers/__init__.py
  cve_bin_tool/checkers/dotnet.py
  test/condensed-downloads/dotnet-runtime-7.0-7.0.11-1.fc39.aarch64.rpm.tar.gz
  test/test_data/dotnet.py
Labels: awaiting CI

#3885 fix: improve bandit config #3830
  .pre-commit-config.yaml
  bandit.conf
  cve_bin_tool/cve_scanner.py
  cve_bin_tool/cvedb.py
  cve_bin_tool/version_signature.py
  setup.cfg
  test/test_cvedb.py
Labels: awaiting CI

#3928 fix: Use colon as delimiter in CBT URN for better compatibility
  cve_bin_tool/input_engine.py
  cve_bin_tool/output_engine/__init__.py
  doc/MANUAL.md
  test/test_input_engine.py
  test/test_output_engine.py
  test/vex/bad.vex
  test/vex/test_triage.vex
  test/vex/test_triage_cyclonedx_case13.vex
  test/vex/test_triage_triage_input.vex
Labels: awaiting maintainer

#3891 fix: Added docstrings to validator.py
  cve_bin_tool/validator.py
Labels: awaiting maintainer
