Repository intel/cve-bin-tool, pull requests merged in 2024-08, with the labels that each got.

#4312 fix: TypeError in fuzz_python_requirement_parser in fuzzing reports #…
  fuzz/fuzz_cargo_lock.py
  fuzz/fuzz_composer_lock.py
  fuzz/fuzz_cpanfile.py
  fuzz/fuzz_cyclonedx.py
  fuzz/fuzz_gemfile_lock.py
  fuzz/fuzz_go.py
  fuzz/fuzz_intermediate_report_merge.py
  fuzz/fuzz_package_list_parser.py
  fuzz/fuzz_package_lock.py
  fuzz/fuzz_package_resolved.py
  fuzz/fuzz_pkg_info.py
  fuzz/fuzz_pom_xml.py
  fuzz/fuzz_pubspec_lock.py
  fuzz/fuzz_python_requirement_parser.py
  fuzz/fuzz_renv_lock.py
Labels: awaiting maintainer

#3873 feat: checker-experiment
  experiments/checker-experiment.py
Labels: awaiting CI

#4327 test: skip `test_language_package` in long tests
  test/test_language_scanner.py
  triage.json
Labels: awaiting submitter
